#include <iostream>
#include <cmath>
#include <vector>
#include <algorithm>
#include <fstream>

// --- 0. HELPER FUNCTIONS & CONSTANTS ---
const double PI = 3.14159265358979323846;

double deg2rad(double degrees) {
    return degrees * (PI / 180.0);
}

double rad2deg(double radians) {
    return radians * (180.0 / PI);
}

// --- PHASE 1: ASTRONOMICAL SOLAR GEOMETRY ---
struct SunPosition {
    double zenith_angle;  // theta_z (radians)
    double azimuth_angle; // gamma_s (radians)
    double declination;   // delta (radians)
    double hour_angle;    // omega (radians)
};

// Calculates where the sun is in the sky for Kharagpur
SunPosition calculate_sun_position(int day_of_year, double solar_time_hours) {
    SunPosition sun;
    
    // Kharagpur Latitude (22.33 N)
    double latitude = deg2rad(22.33); 
    
    // 1. Declination Angle (delta)
    double B = deg2rad((360.0 / 365.0) * (day_of_year - 81));
    sun.declination = deg2rad(23.45 * sin(B));
    
    // 2. Hour Angle (omega): 15 degrees per hour from Solar Noon
    sun.hour_angle = deg2rad(15.0 * (solar_time_hours - 12.0));
    
    // 3. Zenith Angle (theta_z)
    double cos_zenith = sin(latitude) * sin(sun.declination) + 
                        cos(latitude) * cos(sun.declination) * cos(sun.hour_angle);
    sun.zenith_angle = acos(cos_zenith);
    
    // 4. Solar Azimuth (gamma_s)
    double cos_azimuth = (sin(latitude) * cos_zenith - sin(sun.declination)) / 
                         (cos(latitude) * sin(sun.zenith_angle));
    
    // Clamp to avoid NaN errors
    cos_azimuth = std::max(-1.0, std::min(1.0, cos_azimuth)); 
    sun.azimuth_angle = acos(cos_azimuth);
    
    // Adjust Azimuth based on morning/afternoon
    if (solar_time_hours > 12.0) {
        sun.azimuth_angle = 2.0 * PI - sun.azimuth_angle;
    }
    
    return sun;
}

// --- PHASE 2: MAIN LENGTH SWEEP ---
int main() {
    // Kharagpur parameters
    double aperture_width = 1.550;     // w
    double focal_length = 0.8;         // f
    double optical_efficiency = 0.35; 

    std::cout << "Sweeping Collector Length to analyze End Loss..." << std::endl;

    std::ofstream outFile("length_vs_end_loss.csv");
    outFile << "Collector_Length_m,Annual_Yield_kWh,Daily_End_Loss_Ratio_mu\n";

    // Sweep Length (L) from 2 meters to 50 meters
    for (double current_length = 2.0; current_length <= 50.0; current_length += 0.5) {
        
        double annual_energy_Joules = 0.0;
        double total_numerator_integral = 0.0;   
        double total_denominator_integral = 0.0;

        for (int step = 0; step < 35040; step++) {
            int day_of_year = (step / 96) + 1;
            double solar_time = (step % 96) * 0.25;
            
            // Mock Weather Data
            double DNI = (solar_time >= 9.0 && solar_time <= 15.0) ? 1600.0 : 0.0;
            
            if (DNI > 0) {
                SunPosition sun = calculate_sun_position(day_of_year, solar_time);
                if ((sun.zenith_angle * 180.0 / PI) > 90.0) continue;

                double altitude = (PI / 2.0) - sun.zenith_angle;
                double psi = 0.0; // North-South alignment

                // Calculate geometry
                double root_term = sqrt(pow(sin(sun.azimuth_angle + psi), 2) + pow(tan(altitude), 2));
                double tan_theta = cos(sun.azimuth_angle + psi) / root_term;
                double cos_theta = cos(altitude) * root_term;

                // Average optical end loss length
                double L_oel_av = (focal_length + pow(aperture_width, 2) / (48.0 * focal_length)) * std::abs(tan_theta);
                
                // --- THE CRITICAL CALCULATION ---
                // Instantaneous end loss ratio based on current loop length
                double mu_oel = std::min(1.0, L_oel_av / current_length);

                double time_step_seconds = 900.0; 
                total_numerator_integral += (mu_oel * DNI * cos_theta * time_step_seconds);
                total_denominator_integral += (DNI * cos_theta * time_step_seconds);

                // Energy generated by this specific row length
                double active_lit_length = current_length - std::min(current_length, L_oel_av);
                double power_watts = DNI * cos_theta * aperture_width * active_lit_length * optical_efficiency;
                
                annual_energy_Joules += (power_watts * time_step_seconds);
            }
        }

        // Final Integrated End Loss Ratio for this specific Length
        double mu_oel_d = (total_denominator_integral > 0) ? (total_numerator_integral / total_denominator_integral) : 0;
        double annual_yield_kWh = annual_energy_Joules / 3600000.0;

        outFile << current_length << "," << annual_yield_kWh << "," << (mu_oel_d * 100.0) << "\n";
        
        std::cout << "Length: " << current_length << "m | End Loss Ratio: " << (mu_oel_d * 100.0) << "%" << std::endl;
    }

    outFile.close();
    std::cout << "Data saved to 'length_vs_end_loss.csv'." << std::endl;
    return 0;
}
